[server]
runOnSave = false
[theme]
primaryColor = "#1B365D"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
pageTitle = "Project Feasibility Study"
pageIcon = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAA0lBMVEX///////3///v///nh3+a8uM+dl7i0sMvb2eP6+fuhnbyJgq3T0NzIxc7T0duVj7fz8fb///65tdCKhqPU0eOjoLo0K3IAAGAAAGQeCWwAAF0pHHCRj6eWkbCrp8T///jHxNQAAF8wJHDk4OsAAFhDOnp9dqV/dq5ZUn8AAGy2tMKkncUhA2s3LXp6dZk6Mm3y8u1cV3k1KIBSSnsnG2QnF3EqFm8kEnGsp8clE2l7d5NhWI9vaZfFwdcVAGRtZpdIPoBbUY1dUZdANXyHhZ9UTXkhcAVhAAAB2klEQVR4AVWTBYLDIBAAF1Li7lKj7u6u///SQf0mnsHZhQcIYwHniMiQZPaBEPyAFVUjukGIYRJLtIWvcQBczw/CKE7iOM3yeqH4I0taWaUVtSqoNblarMcFs6FgeCI05Va7AyCjLs05DpR7fXmgAAMDaPKwPwLSTyGo5aCuAmq15QbvDmHXGE9AmdIkY7IK/XhoQ6tvqohpxQvaI2XWni9ecpmw+9wTbQfwyow7MGVu+ZLrLAkdveZbGJAWrJEbJ4zlUy4W81iEqWcB5Ei9AJvteLvd7l41mZ3rVrbXoWxQ/bNOb7lY0kOsqxCYqaJvj5wdrN6ScSAiiGXaOdYOD8gg5bL3JAi4ZHWeHE+0ivpL9jY47pbF4NEsvCnWqrhfhwcZER8Dsk9nzuVypazZ7Ljdnn27phefU5GekMajzyTpHRBJ9iZfhMzGDgcj9bsI51sBoLTyk4imcUSj+Lt8YKQ6Xz628LFVDHvz+WfhWeNrtvAYHMHdt66g3P9t2TQ0VQcBAtByw8kIOteIS77ZzvQgN75hMm5LgGWhyySg8uEqNxTnG2ABDzA2Wv8dYKVPaDqupwchjXvtuFYp+IWVw/++EZSV5pYN0jF0oqk2hh8EtgqfdACMkACcP53URMeBXmLKAAAAAElFTkSuQmCC"
